name: Deploy to Droplet

on:
  push:
    branches:
      - main          # triggers on every push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Digital Ocean Droplet
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd ~/fyp_neurotrace
            git pull origin main
            source neurotrace_app/backend/venv/bin/activate
            pip install -r neurotrace_app/backend/requirements.txt --quiet
            systemctl restart tremora
            echo "Deploy complete"